kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hivemr3
  name: workdir-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
